version: '3.8'

services:
    web-backend:
      container_name: web-backend
      image: web-backend
      build: ../../part1/Exercise_1.13/
      ports:
        - "8000:8000"
      #env_file:
      #  - .env
      environment:
        PORT: 8000
        REDIS_HOST: web-redis
        REQUEST_ORIGIN: "http://localhost"
        POSTGRES_HOST: web-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Firmly3ought7pawn
        POSTGRES_DATABASE: postgres
      expose:
        - 8000
      networks:
        - container-network
    web-redis:
      container_name: web-redis
      image: redis:latest
      networks:
        - container-network
    web-frontend:
      container_name: web-frontend
      image: web-frontend
      build: ../../part1/Exercise_1.12/ 
      #command:
      #  - /usr/local/bin/serve -s -l 5000 build
      ports:
        - "5000:5000"
      expose:
        - "5000"
      networks:
        - container-network
      environment:
        REACT_APP_BACKEND_URL: http://localhost:80/api
    web-db:
      container_name: web-db
      image: postgres:latest
      restart: unless-stopped
      networks:
        - container-network
      volumes:
        # NOTE: Bind mount doesn't currently work in Fedora 37? in rw mode?
        #- type: bind
        #  source: ./static
        #  target: /var/lib/postgresql/data
        - web-db-pgsql:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: Firmly3ought7pawn
    web-proxy:
      image: nginx:latest
      expose: 
        - 80
      ports:
        - "80:80"
      networks:
        - container-network
      volumes:
        - /home/mk/mooc/docker/part2/Exercise_2.8/nginx.conf:/etc/nginx/nginx.conf:Z
        #- type: bind
        #  source: ./nginx.conf
        #  target: /etc/nginx/nginx.conf
        # Kludge to copy file, because bind mount has problems
volumes:
  web-db-pgsql:
    name: "web-db-pgsql"
networks:
  container-network: 
    external:
      name: container-network